spring.application.name=LibraryManagementSystem
spring.datasource.url=jdbc:mysql://localhost:3306/library
spring.datasource.username=root
spring.datasource.password=@Mir4448
spring.jpa.hibernate.ddl-auto=update